version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  
"app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  
"app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  detekt:
    <<: *android_config
    steps:
      - checkout
      - *attach_release_workspace
      - *restore_cache
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Run Detekt Checkstyle
          command: ./gradlew detekt
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/

  test_unit:
      <<: *android_config
      steps:
        - checkout
        - *attach_release_workspace
        - *restore_cache
        - run:
           name: Chmod permissions
           command: sudo chmod +x ./gradlew
        - run:
            name: Run unit tests
            command: ./gradlew test -no-daemon -Pkotlin.incremental=false --max-workers=2
        - store_artifacts:
            path: app/build/reports/
            destination: /reports/
        - store_test_results:
            path: app/build/test-results/
            destination: /test-results/

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*/
      - detekt:
          requires:
              - build
          filters:
            tags:
              only: /^.*/
      - test_unit:
          requires:
              - build
          filters:
            tags:
              only: /^.*/